services:
  app:
    restart: always
    depends_on: 
      - postgres

    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
     
    ports:
      - 8080:8080
    
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:17.2

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=music
    ports:
      - 5432:5432

    networks:
      - app-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - SWAGGER_JSON=/swagger/openapi.yaml
    volumes:
      - ../docs/openapi.yaml:/swagger/openapi.yaml # Map the correct path
    ports:
      - 8082:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
